# Generated by Django 3.1.1 on 2020-12-09 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
