# Generated by Django 3.1.2 on 2020-12-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0004_auto_20201212_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='enrolled_participant',
            field=models.ManyToManyField(blank=True, null=True, to='event_handler.Participant', verbose_name='Participant that that have enrolled for the event '),
        ),
        migrations.AlterField(
            model_name='participant',
            name='event_reg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_handler.event'),
            preserve_default=False,
        ),
    ]
