# Generated by Django 3.1.2 on 2020-12-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0006_auto_20201212_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
