# Generated by Django 3.1.2 on 2020-12-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0007_auto_20201212_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_handler.participant')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_handler.event')),
            ],
        ),
    ]
