# Generated by Django 3.1.2 on 2020-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0008_auto_20201212_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='A'),
            preserve_default=False,
        ),
    ]
