# Generated by Django 3.1.2 on 2020-12-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0009_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
