# Generated by Django 3.1.2 on 2020-12-12 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0010_auto_20201212_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ticket_no',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
