# Generated by Django 3.1.2 on 2020-12-14 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_handler', '0011_auto_20201212_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ticket_no',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
